//! Build-time identity constants for `anc` itself.
//!
//! `ANC_VERSION` is the crate version (`CARGO_PKG_VERSION`). `ANC_COMMIT` is the
//! short Git SHA captured at build time, or `None` for builds outside a Git
//! checkout (e.g. `cargo install` from crates.io). Both surface in the
//! scorecard's `anc.{version, commit}` block.
//!
//! Generated by `build.rs` into `$OUT_DIR/build_info.rs`. See `emit_build_info`
//! in `build.rs` for the rerun-watch rationale that keeps `ANC_COMMIT` from
//! going stale across local commits.

include!(concat!(env!("OUT_DIR"), "/build_info.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn anc_version_matches_cargo_pkg_version() {
        // The build script must populate `ANC_VERSION` from `CARGO_PKG_VERSION`.
        // If they ever diverge, the scorecard's `anc.version` would lie about
        // which crate version produced it — silently.
        assert_eq!(ANC_VERSION, env!("CARGO_PKG_VERSION"));
    }

    #[test]
    fn anc_version_is_non_empty() {
        assert!(!ANC_VERSION.is_empty());
    }

    #[test]
    fn anc_commit_when_present_looks_like_short_sha() {
        // Best-effort capture: in a Git checkout we expect a non-empty short
        // SHA (7+ hex chars by default, but `git rev-parse --short` may emit
        // longer prefixes for repos with collisions). For released-from-tarball
        // builds, `None` is the correct answer and this test happily passes.
        if let Some(sha) = ANC_COMMIT {
            assert!(!sha.is_empty(), "ANC_COMMIT must not be Some(\"\")");
            assert!(
                sha.chars().all(|c| c.is_ascii_hexdigit()),
                "ANC_COMMIT must be hex digits only, got {sha:?}",
            );
        }
    }
}
